### ISSUE TITLE
UnpicklingError when loading checkpoint file

### ISSUE THREAD

**Issue by ayutaz** [kotoba-tech/kotoba-speech-release#1]
Thank you for publishing the wonderful library of TTS. I am running this at hand, but I am unable to perform inference with the following error.
I apologize for the inconvenience, but could you please let me know if there is a solution to this problem?
Or, could you give us information on the ver. of pytorch, cuda, etc. in the environment in which you are running?

# Description

I encountered an UnpicklingError when trying to run the fast_inference.py script with the --model_name kotoba-tech/kotoba-speech-v0.1 argument. The error occurs when the script attempts to load the checkpoint file using torch.load().

The relevant part of the error traceback is as follows:

```sh
Traceback (most recent call last):
File "/home/jovyan/kotoba-speech-release/fam/llm/fast_inference.py", line 151, in <module>
    tts = tyro.cli(TTS)
  File "/home/jovyan/kotoba-speech-release/venv/lib/python3.10/site-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/home/jovyan/kotoba-speech-release/venv/lib/python3.10/site-packages/tyro/_cli.py", line 454, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/jovyan/kotoba-speech-release/venv/lib/python3.10/site-packages/tyro/_calling.py", line 241, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords # type: ignore
  File "/home/jovyan/kotoba-speech-release/fam/llm/fast_inference.py", line 69, in __init__
    self.llm_second_stage = Model(
  File "/home/jovyan/kotoba-speech-release/fam/llm/inference.py", line 89, in __init__
    self._init_model()
  File "/home/jovyan/kotoba-speech-release/fam/llm/inference.py", line 101, in _init_model
    checkpoint = torch.load(self.config.ckpt_path, map_location=self.config.device)
  File "/home/jovyan/kotoba-speech-release/venv/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/jovyan/kotoba-speech-release/venv/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

# Environment
* Operating System:  Ubuntu22.02
* Python version: 3.10.12
* pytorch-lightning: 2.2.1
* kotoba-speech-release version: 0.1

# Steps to Reproduce
1. Clone the kotoba-speech-release repository.
2. Install the required dependencies.
3. Run the following command:

```sh
python -i fam/llm/fast_inference.py --model_name kotoba-tech/kotoba-speech-v0.1
```

**Comment by kojimano** [comment]
Hi @ayutaz! Thanks for trying out our code. Here are the relevant package versions:
> pytorch-lightning==2.2.1
pytorch-triton==3.0.0+989adb9a29
torch==2.4.0.dev20240321+cu121

If this issue still persists after updating the libraries, please let us know. We're happy to do a deeper dive :)

**Comment by jungokasai** [comment]
Closing this, as this is a package version issue. Let us know if the problem still persists.

**Comment by jungokasai** [comment]
Closing this, as this is a package version issue. Let us know if the problem still persists.
